name: 安卓打包
on:
  workflow_dispatch:
    inputs:
        version:
          description: 打包
          required: true
          type: boolean
          default: false

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
          - name: 读取仓库
            uses: actions/checkout@v4

          - name: 安装node
            uses: actions/setup-node@v4
            with:
              node-version: 23

          - name: 安装pnpm
            uses: pnpm/action-setup@v4
            with:
              version: 10

          - name: 安装java
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin'
              java-version: '21'

          - name: 安装 Android SDK
            uses: android-actions/setup-android@v3

          - name: 安装 NDK
            run: sdkmanager "ndk;27.2.12479018"

          - name: 安装 Rust 和 需要的架构
            uses: dtolnay/rust-toolchain@stable
            with:
              targets: aarch64-linux-android

          - name: 安装依赖
            run: pnpm install

          - name: 打包apk
            run: pnpm tauri android build -t aarch64 --apk
            env:
              NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/27.2.12479018

          - name: 上传构建产物
            uses: actions/upload-artifact@v4
            with:
              name: ta
              path: src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk
