name: 打包
on:
  workflow_dispatch:
    inputs:
      version:
        description: '打包'
        required: true
        type: boolean


jobs:
  build-upload:
    runs-on: windows-latest
    steps:
      - name: 读取仓库
        uses: actions/checkout@v4

      - name: 安装 node
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: 安装 rust
        uses: dtolnay/rust-toolchain@stable

      - name: 安装 pnpm
        run: npm install -g pnpm

      - name: 安装依赖
        run: pnpm install

      - name: 打包tauri
        uses: tauri-apps/tauri-action@v0

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-${{ matrix.platform }}
          path: src-tauri/target/release/bundle/